on:
  workflow_dispatch:
  push:
    branches: [develop]
  pull_request:
    types: [opened, synchronize, reopened]

name: CI Workflow
jobs:
  sonarcloud:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ACCT-global_gokursos-faststore
            -Dsonar.organization=acct-global-github
            -Dsonar.pullrequest.key=${{ github.event.number }}
            -Dsonar.pullrequest.branch=${{ github.HEAD_REF }}
            -Dsonar.pullrequest.base=${{ github.BASE_REF }}
            -Dsonar.pullrequest.github.repository=${{ github.repository }}
            -Dsonar.scm.provider=git
            -Dsonar.coverage.exclusions=**/*.config.js

  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Gatsby Cache Folder
        id: gatsby-cache-folder
        uses: actions/cache@v1
        env:
          cache-name: cache-gatsby-cache
        with:
          path: .cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Gatsby Public Folder
        id: gatsby-public-folder
        uses: actions/cache@v1
        env:
          cache-name: cache-gatsby-public
        with:
          path: public/
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Install dependencies
        run: |
          npm install --global yarn
          yarn

      - name: Build
        run: yarn build --log-pages
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          GATSBY_CONTENTFUL_SPACE_ID: ${{secrets.GATSBY_CONTENTFUL_SPACE_ID}}
          GATSBY_CONTENTFUL_CDAPI_TOKEN: ${{secrets.GATSBY_CONTENTFUL_CDAPI_TOKEN}}

  lighthouse:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Chrome
        run: |
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google.list
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y nodejs google-chrome-stable
          export CHROME_PATH=$(which google-chrome-stable)

      - name: Gatsby Public Folder
        id: gatsby-public-folder
        uses: actions/cache@v1
        env:
          cache-name: cache-gatsby-public
        with:
          path: public/
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.8.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
